### ISSUE TITLE
IE11 登陆页面发生了串位

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#1]
IE11 登录页面登陆框发生了串位,并且带来登录功能的缺失。
Edge 正常。
Chrome 正常。
![bug](https://user-images.githubusercontent.com/44855701/48929320-9efb5c80-ef22-11e8-92a2-4439e3f428c5.JPG)

**Comment by nonbotanist** [comment]
按钮位置发生了偏移。
![bug](https://user-images.githubusercontent.com/44855701/48929823-0ddab480-ef27-11e8-8a8d-391ab90a4cc1.JPG)

**Comment by hillockSun** [comment]
![1](https://user-images.githubusercontent.com/26404051/48930919-74af9c00-ef2e-11e8-8e61-47cb53deec1a.PNG)
无法重现 不予解决

**Comment by nonbotanist** [comment]
已经重现，settings.py文件中的 ALLOWED_HOSTS = ['*']
初步诊断是，当时用ip访问时产生的错误。

**Comment by hillockSun** [comment]
浏览器默认为IE5 造成的，已解决
