### ISSUE TITLE
导出图标不对

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#14]
可以用下载图标，也可以用excel图标，也可以使用csv图标
![bug2](https://user-images.githubusercontent.com/44855701/48999673-534eea00-f192-11e8-98e5-3d69a836bcb2.JPG)

**Comment by hillockSun** [comment]
已解决

**Comment by nonbotanist** [comment]
但是这个功能不可用了

**Comment by nonbotanist** [comment]
但是这个功能不可用了，无法导出了

**Comment by nonbotanist** [comment]
但是这个功能不可用了，无法导出了
