### ISSUE TITLE
版权信息不对

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#15]
dxc不具有版权，所以页脚的版权信息不对。可以写DXC制作和提供。并讲DXC的图标放置在左侧的制作信息附近。
右侧可以时华晨宝马的图标。
![bug2](https://user-images.githubusercontent.com/44855701/49000138-a2e1e580-f193-11e8-9bf6-f212f5110709.JPG)

**Comment by hillockSun** [comment]
已解决

**Comment by nonbotanist** [comment]
1. 左侧缺少DXC图标
2. 英文请改成Made and Provided by DXC(图标，超链接到DXC官网).
