### ISSUE TITLE
登录页面样式的变更

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#17]
请见图片效果，登录的黑色背景条改成蓝色。
就是imdc的蓝色
![bug2](https://user-images.githubusercontent.com/44855701/49055301-14707100-f232-11e8-9465-8c3a6da5ae03.JPG)
![368103844](https://user-images.githubusercontent.com/44855701/49055397-62857480-f232-11e8-9ce5-ab5b5ecf69d5.jpg)

**Comment by hillockSun** [comment]
已解决
