### ISSUE TITLE
浏览器中的DXC图标，更换为宝马图标

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#24]
![image](https://user-images.githubusercontent.com/44855701/49714837-721ca880-fc89-11e8-97be-0c795ad276a9.png)
地址栏前和标题
![image](https://user-images.githubusercontent.com/44855701/49714858-8a8cc300-fc89-11e8-8463-42a9fe4e3351.png)

**Comment by hillockSun** [comment]
已解决
