### ISSUE TITLE
图标滑动效果不对

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#27]
![image](https://user-images.githubusercontent.com/44855701/49715741-4e0e9680-fc8c-11e8-8721-feea6733c4b8.png)
![image](https://user-images.githubusercontent.com/44855701/49715796-73030980-fc8c-11e8-85d5-bc9f3dfae3c5.png)
鼠标滑动时不时小手的图标

**Comment by hillockSun** [comment]
已解决
