### ISSUE TITLE
CleanUP Rules 的Folder校验

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#3]
我希望的地址是
\\bmwbrill.cn\DDFS1\IMDC\UVI\KA\DS\MDM.Test\TEMP
但是无法选择，也无法直接填写
![Uploading bug.JPG…]()

**Comment by hillockSun** [comment]
无法重新

**Comment by nonbotanist** [comment]
可以远程展示

**Comment by hillockSun** [comment]
IE11 有关的兼容问题都暂时不予解决 电脑装不上IE1没办法调试

**Comment by hillockSun** [comment]
![3](https://user-images.githubusercontent.com/26404051/48931083-74fc6700-ef2f-11e8-9d5c-36e266ae7569.PNG)
不予解决

**Comment by nonbotanist** [comment]
只选择文件夹，校验文件夹路径

**Comment by hillockSun** [comment]
已解决

**Comment by hillockSun** [comment]
请设置：
1. 单击菜单工具->Internet选项->安全->受信任站点->站点->把此网站设为可信站点
2. 在自定义级别->对没有标记为安全的ActiveX控件进行初始化和脚本运行"----"启用"

**Comment by nonbotanist** [comment]
这个提示能否更改？

**Comment by nonbotanist** [comment]
用户可能会使用谷歌浏览器和edge

**Comment by nonbotanist** [comment]
ie的这个设置在bba是被禁止的。
![image](https://user-images.githubusercontent.com/44855701/49720490-d72cca00-fc9a-11e8-8353-e649d1e24b01.png)

**Comment by hillockSun** [comment]
1.  这个提示不能更改， 是浏览器内置提示，也没有异常抛出
2. 目前能IE可以用这个
3. IE 可以修改，我和jason已经试过了
