### ISSUE TITLE
页面Title统一

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#38]
![image](https://user-images.githubusercontent.com/44855701/49843752-3275ce00-fdfb-11e8-9794-f636b25e36b5.png)
统一更换为IMDC Clean-Up Tool

**Comment by hillockSun** [comment]
已解决

**Comment by nonbotanist** [comment]
登录页没改
![image](https://user-images.githubusercontent.com/44855701/49923608-06d41000-feef-11e8-9ed9-9dadb028df87.png)
