### ISSUE TITLE
history 错误

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#40]
![image](https://user-images.githubusercontent.com/44855701/49913574-f5780d00-fec8-11e8-9ad9-c4e5241b0bce.png)
name => rule name
rule type =>regex type
path =>绝对路径
Cleanup => Cleaned
Count =>Number
Cleaned Files Count ,Cleaned Files Size 两列靠右绝对宽度，缩到最小的宽度

**Comment by hillockSun** [comment]
已解决
