### ISSUE TITLE
路径放在输入框的前面

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#48]
![image](https://user-images.githubusercontent.com/44855701/49923253-db9cf100-feed-11e8-88b1-5259ef2e6b4d.png)
路径放在输入框的前面。我们可以限制长度的。长度要求
\\bmwbrill.cn\DDFS1\IMDC\ 必须完整显示
如果大约这个长度就显示最前和最后的部分：例如
\\bmwbrill.cn\DDFS1\IMDC\BBT-E-3\G038 显示为\\bmwbrill.cn\...\G038\ ,鼠标悬停或双击时，浮出提示全路径。
文本框的要求：悬停或双击时提示全路径。

**Comment by hillockSun** [comment]
已解决
