### ISSUE TITLE
Status未显示内容

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#6]
在job schedule中的status未有任何
![bug](https://user-images.githubusercontent.com/44855701/48930502-d4f10e80-ef2b-11e8-8a64-3075acdc69b6.JPG)

**Comment by hillockSun** [comment]
![5](https://user-images.githubusercontent.com/26404051/48931188-efc58200-ef2f-11e8-9c19-a657b5151416.PNG)
已解决
