### ISSUE TITLE
主页登陆界面需要加一个“回车登陆“功能

### ISSUE THREAD

**Issue by AaronDeng0531** [dxc-bba/yardman#62]
![default](https://user-images.githubusercontent.com/46098884/50468713-3b15f900-09e4-11e9-9dc4-d7aed80d5c2f.png)

**Comment by luckymoment** [comment]
Fixed.

**Comment by nonbotanist** [comment]
wait for requester's verification

**Comment by AaronDeng0531** [comment]
done
