### ISSUE TITLE
第一列内容左对齐

### ISSUE THREAD

**Issue by AaronDeng0531** [dxc-bba/yardman#65]
![default](https://user-images.githubusercontent.com/46098884/50504553-48e18200-0aa9-11e9-94d6-d0f2551c2e68.png)

**Comment by luckymoment** [comment]
Fixed.

**Comment by nonbotanist** [comment]
wait for requester's verification

**Comment by AaronDeng0531** [comment]
![capture](https://user-images.githubusercontent.com/46098884/50577942-a856dd80-0e6d-11e9-90b8-910dbfdb76cb.JPG)

**Comment by AaronDeng0531** [comment]
clean up job列左对齐了

**Comment by AaronDeng0531** [comment]
clean up job列左对齐了
