### ISSUE TITLE
job显示上无法自己停止

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#67]
![image](https://user-images.githubusercontent.com/44855701/50532189-c3191180-0b50-11e9-90ec-ff7bdc8f6513.png)
在大约24个小时后，系统仍显示job还在运行。
![image](https://user-images.githubusercontent.com/44855701/50532230-74b84280-0b51-11e9-91a8-7e81ee83d991.png)
监控后台发现有活动的页面ajax请求。看上去job已经结束，只是显示不正确。

**Comment by AaronDeng0531** [comment]
What's the status going?

**Comment by AaronDeng0531** [comment]
done
