### ISSUE TITLE
Rule 的编辑和列表内显示的的cyclebin状态不统一

### ISSUE THREAD

**Issue by nonbotanist** [dxc-bba/yardman#7]
Rule 的编辑和列表内显示的的cyclebin状态不统一
![bug](https://user-images.githubusercontent.com/44855701/48930566-606a9f80-ef2c-11e8-9626-44bfa373e4ba.JPG)
![bug2](https://user-images.githubusercontent.com/44855701/48930568-63659000-ef2c-11e8-93bd-c76deb5a72a1.JPG)

**Comment by hillockSun** [comment]
这个不是当时开会的时候说的TRUE不显示√， 请确认需求后回复，需不需要修改

**Comment by hillockSun** [comment]
已解决
