### ISSUE TITLE
平台设定的job时间是周三11点，但是周一cleanup jobs monitor中就有job正在进行

### ISSUE THREAD

**Issue by AaronDeng0531** [dxc-bba/yardman#71]

**Comment by AaronDeng0531** [comment]
![capture1](https://user-images.githubusercontent.com/46098884/50811599-186fd280-134a-11e9-86ad-b68e680655a5.JPG)

**Comment by AaronDeng0531** [comment]
在服务器中重启服务之后，job自动运行

**Comment by luckymoment** [comment]
Sorry the test indicator was true so that the job will start automatic, already updated.
